In [6]:
import sys
sys.path.append("..")
from utils import *
import numpy as np

In [7]:
for i in range(16):
    print(f_1D_transform(i,key=3,N = 16))

1
4
7
10
13
0
3
6
9
12
15
2
5
8
11
14


In [13]:

o_table = np.array(range(64*64)).reshape(64,64)
print(o_table[28:32,28:32])

[[1820 1821 1822 1823]
 [1884 1885 1886 1887]
 [1948 1949 1950 1951]
 [2012 2013 2014 2015]]


In [14]:
lu_table = create_luck_up_table(64,64,13)
print(lu_table[28:32,28:32])

[[3379 3440 3575 3636]
 [3187 3248 3383 3444]
 [4019 4080 3191 3252]
 [3827 3888 4023 4084]]


In [16]:
for i in range(28,36):
    for j in range(28,36):
        print(int(o_table[i,j]/64),o_table[i,j]%64)
    print("next")

28 28
28 29
28 30
28 31
28 32
28 33
28 34
28 35
next
29 28
29 29
29 30
29 31
29 32
29 33
29 34
29 35
next
30 28
30 29
30 30
30 31
30 32
30 33
30 34
30 35
next
31 28
31 29
31 30
31 31
31 32
31 33
31 34
31 35
next
32 28
32 29
32 30
32 31
32 32
32 33
32 34
32 35
next
33 28
33 29
33 30
33 31
33 32
33 33
33 34
33 35
next
34 28
34 29
34 30
34 31
34 32
34 33
34 34
34 35
next
35 28
35 29
35 30
35 31
35 32
35 33
35 34
35 35
next


In [15]:
for i in range(28,36):
    for j in range(28,36):
        print(int(lu_table[i,j]/64),lu_table[i,j]%64)
    print("next")

52 51
53 48
55 55
56 52
28 30
29 27
30 24
16 31
next
49 51
50 48
52 55
53 52
25 30
26 27
27 24
29 31
next
62 51
63 48
49 55
50 52
22 30
23 27
24 24
26 31
next
59 51
60 48
62 55
63 52
19 30
20 27
21 24
23 31
next
8 51
9 48
11 55
12 52
32 30
33 27
34 24
36 31
next
5 51
6 48
8 55
9 52
45 30
46 27
47 24
33 31
next
2 51
3 48
5 55
6 52
42 30
43 27
44 24
46 31
next
15 51
0 48
2 55
3 52
39 30
40 27
41 24
43 31
next
